# Generated by Django 4.2.5 on 2023-10-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0003_category_menutbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
