# Generated by Django 4.2.5 on 2023-10-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0006_alter_person_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
