# Generated by Django 4.2.5 on 2023-11-02 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0007_alter_person_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='menutbl',
            name='cidf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='page1.category'),
        ),
        migrations.AlterField(
            model_name='menutbl',
            name='cid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
