# Generated by Django 4.2.5 on 2023-11-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0010_remove_menutbl_cn_alter_menutbl_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
