# Generated by Django 4.2.5 on 2023-11-17 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0011_alter_category_cid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_no', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='subcategory',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menutbl',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('c_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='page1.person')),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='page1.menutbl')),
                ('t_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='page1.table_details')),
            ],
        ),
    ]
