# Generated by Django 4.2.5 on 2023-11-22 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page1', '0013_alter_cart_c_id_alter_cart_quantity_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='o_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='t_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='page1.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='c_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='page1.Cart', to='page1.menutbl'),
        ),
    ]
