# Generated by Django 4.2.5 on 2023-11-22 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0014_rename_order_date_order_o_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='t_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='page1.table_details'),
        ),
    ]
