# Generated by Django 4.2.5 on 2023-11-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0017_cart_order_id_remove_order_items_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
