# Generated by Django 4.2.5 on 2023-11-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0018_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='c_id',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='t_id',
            new_name='table_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='c_id',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='o_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='t_id',
            new_name='table_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='cart',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='incart',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cart',
            name='prepared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
