# Generated by Django 4.2.5 on 2023-11-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0019_rename_c_id_cart_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='old',
            field=models.BooleanField(default=False),
        ),
    ]
