# Generated by Django 4.2.5 on 2023-11-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0022_order_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ready_to_deliver',
            field=models.BooleanField(default=False),
        ),
    ]
