# Generated by Django 4.2.5 on 2023-12-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0025_order_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='started_to_prepare',
            field=models.BooleanField(default=False),
        ),
    ]
