# Generated by Django 4.2.5 on 2024-02-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0027_tablereservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablereservation',
            name='reject',
            field=models.BooleanField(default=False),
        ),
    ]
