# Generated by Django 4.2.5 on 2024-02-09 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0029_tablereservation_timeout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablereservation',
            old_name='time',
            new_name='timein',
        ),
    ]
