# Generated by Django 4.2.5 on 2024-02-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0031_remove_tablereservation_additionalrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablereservation',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='reason',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
