# Generated by Django 4.2.5 on 2024-03-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0033_customization_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customization',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
