# Generated by Django 4.2.5 on 2024-04-14 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0036_tablereservation_table_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablereservation',
            name='table_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='page1.table_details'),
        ),
    ]
