# Generated by Django 4.2.5 on 2024-04-14 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0037_alter_tablereservation_table_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserved_Tables_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('reservation_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='page1.tablereservation')),
                ('table_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='page1.table_details')),
            ],
        ),
    ]
