# Generated by Django 4.2.5 on 2024-04-16 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page1', '0038_reserved_tables_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selected_customization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('cart_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='page1.cart')),
                ('customization_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='page1.customization')),
                ('option_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='page1.options')),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='page1.order')),
            ],
        ),
    ]
