from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

"""urlpatterns = [
    path('',views.index,name="index"),
    path('menu',views.menu,name="menu"),
    path('accounts/login/',views.loginpage,name="loginpage"),
    path('accounts/login/signup',views.signup,name="signup"),
    path('chome',views.chome,name="chome"),
    path('staffhome',views.staffhome,name="staffhome"),
    path('accounts/login/logout_user',views.logout_user,name="logout_user"),
    path('adminhome',views.adminhome,name="adminhome"),
    path('customerprofile',views.customerprofile,name="customerprofile"),
    path('a_add_person',views.a_add_person,name="a_add_person"),
    path('a_view_person',views.a_view_person,name="a_view_person"),
    path('reset_password/', auth_views.PasswordResetView.as_view(), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]"""

urlpatterns = [
    path('',views.index,name="index"),
    path('menu',views.menu,name="menu"),
    path('accounts/login/',views.loginpage,name="loginpage"),
    path('signup',views.signup,name="signup"),
    path('accounts/profile/',views.chome,name="chome"),
    path('staffhome',views.staffhome,name="staffhome"),
    path('logout_user',views.logout_user,name="logout_user"),
    path('adminhome',views.adminhome,name="adminhome"),
    path('customerprofile',views.customerprofile,name="customerprofile"),
    path('a_add_person',views.a_add_person,name="a_add_person"),
    path('a_view_person',views.a_view_person,name="a_view_person"),
    path('changepassword',views.changepassword,name="changepassword"),
    path('delete_user',views.delete_user,name="delete_user"),
    path('a_add_items',views.a_add_items,name="a_add_items"),
    path('a_view_category',views.a_view_category,name="a_view_category"),
    path('a_view_menu',views.a_view_menu,name="a_view_menu"),
    path('a_add_category',views.a_add_category,name="a_add_category"),
    path('a_edit_menu_item/<int:item_id>/',views.a_edit_menu_item,name="a_edit_menu_item"),
    path('a_view_subcategory/<int:item_id>/',views.a_view_subcategory,name="a_view_subcategory"),
    path('a_edit_subcategory/<int:item_id>/',views.a_edit_subcategory,name="a_edit_subcategory"),
    path('get_category_subcategory_data/', views.get_category_subcategory_data, name='get_category_subcategory_data'),
    path('a_add_subcategory/<int:item_id>/',views.a_add_subcategory,name="a_add_subcategory"),
    path('get_subcategories/', views.get_subcategories, name='get_subcategories'),
    path('a_status_menu/<int:item_id>/',views.a_status_menu,name="a_status_menu"),
    path('a_edit_category/<int:item_id>/',views.a_edit_category,name="a_edit_category"),
    path('a_status_category/<int:item_id>/',views.a_status_category,name="a_status_category"),
    path('a_search_menu/', views.a_search_menu, name='a_search_menu'),
    path('c_cart_view/', views.c_cart_view, name='c_cart_view'),
    path('c_add_to_cart/<int:item_id>', views.c_add_to_cart, name='c_add_to_cart'),
    path('c_update_cart/<int:item_id>', views.c_update_cart, name='c_update_cart'),
    path('s_profile', views.s_profile, name='s_profile'),
    path('s_view_orders', views.s_view_orders, name='s_view_orders'),
    path('add_to_order', views.add_to_order, name='add_to_order'),
    path('c_order_view', views.c_order_view, name='c_order_view'),
    path('ordered_to_prepared/<int:item_id>', views.ordered_to_prepared, name='ordered_to_prepared'),
    path('prepared_to_ready_to_deliver/<int:item_id>', views.prepared_to_ready_to_deliver, name='prepared_to_ready_to_deliver'),
    path('deliver_order/<int:order_id>', views.deliver_order, name='deliver_order'),
    path('make_payment/<int:order_id>', views.make_payment, name='make_payment'),
    path('c_view_previous_orders', views.c_view_previous_orders, name='c_view_previous_orders'),
    path('a_view_current_orders', views.a_view_current_orders, name='a_view_current_orders'),
    # path('make_old/<int:order_id>', views.make_old, name='make_old'),
    path('a_view_order_history', views.a_view_order_history, name='a_view_order_history'),
    path('get_cart_details/<int:order_id>/', views.get_cart_details, name='get_cart_details'),
    path('payment_status/<int:order_id>/', views.payment_status, name='payment_status'),
    path('c_delefe_from_cart/<int:item_id>', views.c_delefe_from_cart, name='c_delefe_from_cart'),
    path('c_table_reservation', views.c_table_reservation, name='c_table_reservation'),
    path('a_view_table_reservation', views.a_view_table_reservation, name='a_view_table_reservation'),
    # path('a_view_reservation_details', views.a_view_reservation_details, name='a_view_reservation_details'),
    path('c_view_previous_reservations', views.c_view_previous_reservations, name='c_view_previous_reservations'),
    path('a_table_rejection/<int:reservation_id>/', views.a_table_rejection, name='a_table_rejection'),
    path('send_mail_page/<int:reservation_id>/', views.send_mail_page, name='send_mail_page'),
    path('a_view_specific_date_reservations', views.a_view_specific_date_reservations, name='a_view_specific_date_reservations'),
    path('a_view_rejected_reservations', views.a_view_rejected_reservations, name='a_view_rejected_reservations'),
    path('c_cancel_reservation/<int:reservation_id>/', views.c_cancel_reservation, name='c_cancel_reservation'),
    path('c_calorie_detection', views.c_calorie_detection, name='c_calorie_detection'),
    path('a_customization', views.a_customization, name='a_customization'),
    path('a_view_customization/<int:menu_id>/', views.a_view_customization, name='a_view_customization'),
    path('a_add_customizations/<int:menu_id>/', views.a_add_customizations, name='a_add_customizations'),
    path('a_edit_customization/<int:customization_id>/', views.a_edit_customization, name='a_edit_customization'),
    path('a_edit_customization_on_click_btn/<int:customization_id>/', views.a_edit_customization_on_click_btn, name='a_edit_customization_on_click_btn'),
    path('a_delete_customization/<int:customization_id>/', views.a_delete_customization, name='a_delete_customization'),
    path('a_delete_option/<int:option_id>/', views.a_delete_option, name='a_delete_option'),
    path('a_edit_option/<int:option_id>/', views.a_edit_option, name='a_edit_option'),
    path('a_edit_option_on_click_btn/<int:option_id>/', views.a_edit_option_on_click_btn, name='a_edit_option_on_click_btn'),
    path('a_add_option/<int:customization_id>/', views.a_add_option, name='a_add_option'),
    path('a_add_option_onclick/<int:customization_id>/', views.a_add_option_onclick, name='a_add_option_onclick'),
    path('a_add_customizations_onclick/<int:menu_id>/', views.a_add_customizations_onclick, name='a_add_customizations_onclick'),
    path('c_apply_customization/<int:cart_id>/<int:customization_id>/<int:option_id>/', views.c_apply_customization, name='c_apply_customization'),
    path('c_clear_customization', views.c_clear_customization, name='c_clear_customization'),
    # path('c_apply_radiocustomization/<int:cart_id>/<int:customization_id>/<int:option_id>/', views.c_apply_radiocustomization, name='c_apply_radiocustomization'),









    path('reset_password/', auth_views.PasswordResetView.as_view(), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]